services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: AndefRacing-Backend
    restart: unless-stopped
    ports:
      - ${BACKEND_PORTS}
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_EXPIRATION_MILLIS: ${JWT_EXPIRATION_MILLIS}
      SERVLET_MULTIPART_MAX_FILE_SIZE: 10MB
      SERVLET_MULTIPART_MAX_REQUEST_SIZE: 50MB
    depends_on:
      - postgres
      - redis
    volumes:
      - ./uploads:/uploads
    networks:
      - andef-racing-network

  client-frontend:
    build:
      context: ./frontend/AndefRacing-Client-Frontend
      dockerfile: Dockerfile
    container_name: AndefRacing-Client-Frontend
    restart: unless-stopped
    ports:
      - ${CLIENT_FRONTEND_PORTS}
    depends_on:
      - backend
    networks:
      - andef-racing-network

  employee-frontend:
    build:
      context: ./frontend/AndefRacing-Employee-Frontend
      dockerfile: Dockerfile
    container_name: AndefRacing-Employee-Frontend
    restart: unless-stopped
    ports:
      - ${EMPLOYEE_FRONTEND_PORTS}
    depends_on:
      - backend
    networks:
      - andef-racing-network

  postgres:
    image: postgres:16
    container_name: AndefRacing-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORTS}
    volumes:
      - postgres_data_andef_racing:/var/lib/postgresql/data
      - ./src/main/scripts/db/init:/docker-entrypoint-initdb.d
    networks:
      - andef-racing-network

  redis:
    image: redis:8
    container_name: AndefRacing-redis
    restart: unless-stopped
    ports:
      - ${REDIS_PORTS}
    volumes:
      - redis_data_andef_racing:/data
    command: >
      redis-server
      --appendonly yes
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy allkeys-lru
      --requirepass ${REDIS_PASSWORD}
    networks:
      - andef-racing-network

  postgres-test:
    image: postgres:16
    container_name: AndefRacing-postgres-test
    restart: no
    environment:
      POSTGRES_DB: ${POSTGRES_TEST_DB}
      POSTGRES_USER: ${POSTGRES_TEST_USER}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD}
    ports:
      - ${POSTGRES_TEST_PORTS}
    volumes:
      - ./src/main/scripts/db/init:/docker-entrypoint-initdb.d
    networks:
      - andef-racing-network
    profiles:
      - test

volumes:
  postgres_data_andef_racing:
  redis_data_andef_racing:

networks:
  andef-racing-network:
    driver: bridge