-- все схемы
CREATE SCHEMA location;
CREATE SCHEMA info;
CREATE SCHEMA games;
CREATE SCHEMA hr;
CREATE SCHEMA favorite;
CREATE SCHEMA bookings;
CREATE SCHEMA clients;

-- таблицы в location схеме
CREATE TABLE location.region
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE location.city
(
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id SMALLINT     NOT NULL REFERENCES location.region (id),
    name      VARCHAR(100) NOT NULL,

    UNIQUE (region_id, name)
);

-- таблицы в games схеме
CREATE TABLE games.game
(
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100) UNIQUE NOT NULL,
    photo_url TEXT UNIQUE         NOT NULL
);

-- таблицы в info схеме
CREATE TABLE info.club
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id       SMALLINT            NOT NULL REFERENCES location.city (id),
    name          VARCHAR(100) UNIQUE NOT NULL,
    phone         VARCHAR(16)         NOT NULL CHECK (phone ~ '^\+7-\d{3}-\d{3}-\d{2}-\d{2}$'),
    email         TEXT                NOT NULL CHECK (email ~ '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    address       TEXT                NOT NULL,
    cnt_equipment SMALLINT            NOT NULL CHECK (cnt_equipment > 0)
);

CREATE TABLE info.photo
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id         INT      NOT NULL REFERENCES info.club (id),
    url             TEXT     NOT NULL,
    sequence_number SMALLINT NOT NULL,

    UNIQUE (club_id, sequence_number),
    UNIQUE (club_id, url)
);

CREATE TABLE info.game_club
(
    club_id INT      NOT NULL REFERENCES info.club (id),
    game_id SMALLINT NOT NULL REFERENCES games.game (id),

    PRIMARY KEY (club_id, game_id)
);

CREATE TABLE info.price
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id          INT           NOT NULL REFERENCES info.club (id),
    duration_minutes SMALLINT      NOT NULL CHECK (duration_minutes > 0),
    value            NUMERIC(8, 2) NOT NULL CHECK (value > 0),

    UNIQUE (club_id, duration_minutes)
);

CREATE TABLE info.work_schedule
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     INT      NOT NULL REFERENCES info.club (id),
    day_of_week SMALLINT NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    open_time   TIME,
    close_time  TIME,
    is_work_day BOOLEAN  NOT NULL DEFAULT FALSE,

    CHECK (
        (is_work_day = FALSE AND open_time IS NULL AND close_time IS NULL)
            OR
        (is_work_day = TRUE AND open_time IS NOT NULL AND close_time IS NOT NULL AND open_time < close_time)
        ),

    UNIQUE (club_id, day_of_week)
);

CREATE TABLE info.work_schedule_exception
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     INT     NOT NULL REFERENCES info.club (id),
    date        DATE    NOT NULL,
    open_time   TIME,
    close_time  TIME,
    is_work_day BOOLEAN NOT NULL DEFAULT FALSE,
    description TEXT,


    CHECK (
        (is_work_day = FALSE AND open_time IS NULL AND close_time IS NULL)
            OR
        (is_work_day = TRUE AND open_time IS NOT NULL AND close_time IS NOT NULL AND open_time < close_time)
        ),

    UNIQUE (club_id, date)
);

-- таблицы в hr схеме
CREATE TABLE hr.employee
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname       VARCHAR(100)       NOT NULL,
    name          VARCHAR(100)       NOT NULL,
    patronymic    VARCHAR(100),
    phone         VARCHAR(16) UNIQUE NOT NULL CHECK (phone ~ '^\+7-\d{3}-\d{3}-\d{2}-\d{2}$'),
    password      TEXT,
    need_password BOOLEAN            NOT NULL DEFAULT TRUE,
    is_blocked    BOOLEAN            NOT NULL DEFAULT FALSE,

    CHECK ((need_password = TRUE AND password IS NULL) OR (need_password = FALSE AND password IS NOT NULL))
);

CREATE TABLE hr.employee_role
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(30) UNIQUE NOT NULL
);

CREATE TABLE hr.employee_club
(
    club_id          INT      NOT NULL REFERENCES info.club (id),
    employee_id      BIGINT   NOT NULL REFERENCES hr.employee (id),
    employee_role_id SMALLINT NOT NULL REFERENCES hr.employee_role (id),

    PRIMARY KEY (club_id, employee_id, employee_role_id)
);

-- таблицы в clients схеме
CREATE TABLE clients.client
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)       NOT NULL,
    phone      VARCHAR(16) UNIQUE NOT NULL CHECK (phone ~ '^\+7-\d{3}-\d{3}-\d{2}-\d{2}$'),
    password   TEXT               NOT NULL,
    is_blocked BOOLEAN            NOT NULL DEFAULT FALSE
);

-- таблицы и ENUM для bookings схемы
CREATE TYPE bookings.booking_status AS ENUM ('PENDING','PAID','CANCELLED','EXPIRED');

CREATE TABLE bookings.booking
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id                INT                     NOT NULL REFERENCES info.club (id),
    client_id              BIGINT REFERENCES clients.client (id),
    start_datetime         TIMESTAMPTZ             NOT NULL,
    end_datetime           TIMESTAMPTZ             NOT NULL,
    cnt_equipment          SMALLINT                NOT NULL CHECK (cnt_equipment > 0),
    price_value            NUMERIC(10, 2)          NOT NULL CHECK (price_value > 0),
    status                 bookings.booking_status NOT NULL,
    is_walk_in             BOOLEAN                 NOT NULL,
    created_by_employee_id BIGINT REFERENCES hr.employee (id),

    CHECK (start_datetime < end_datetime),
    CHECK (
        (is_walk_in = FALSE AND client_id IS NOT NULL)
            OR
        (is_walk_in = TRUE AND created_by_employee_id IS NOT NULL)
        )
);

-- таблицы для favorite схемы
CREATE TABLE favorite.client_favorite_club
(
    client_id BIGINT NOT NULL REFERENCES clients.client (id),
    club_id   INT    NOT NULL REFERENCES info.club (id),

    PRIMARY KEY (client_id, club_id)
);