--------------------------------------------------------------------------------------------
-- H2 schema for tests (adapted from PostgreSQL schema)
--------------------------------------------------------------------------------------------

CREATE SCHEMA IF NOT EXISTS location;
CREATE SCHEMA IF NOT EXISTS info;
CREATE SCHEMA IF NOT EXISTS games;
CREATE SCHEMA IF NOT EXISTS hr;
CREATE SCHEMA IF NOT EXISTS favorite;
CREATE SCHEMA IF NOT EXISTS bookings;
CREATE SCHEMA IF NOT EXISTS clients;

--------------------------------------------------------------------------------------------
-- Tables in location schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS location.region
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS location.city
(
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_id SMALLINT     NOT NULL,
    name      VARCHAR(100) NOT NULL,

    CONSTRAINT fk_city_region
        FOREIGN KEY (region_id) REFERENCES location.region (id),

    UNIQUE (region_id, name)
);

--------------------------------------------------------------------------------------------
-- Tables in games schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS games.game
(
    id        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      VARCHAR(100) UNIQUE NOT NULL,
    photo_url VARCHAR(1024) UNIQUE NOT NULL,
    is_active BOOLEAN             NOT NULL
);

--------------------------------------------------------------------------------------------
-- Tables in info schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS info.club
(
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_id       SMALLINT            NOT NULL,
    name          VARCHAR(100) UNIQUE NOT NULL,
    phone         VARCHAR(32)         NOT NULL,
    email         VARCHAR(320)        NOT NULL,
    address       VARCHAR(1024)       NOT NULL,
    cnt_equipment SMALLINT            NOT NULL,
    is_open       BOOLEAN             NOT NULL,

    CONSTRAINT fk_club_city
        FOREIGN KEY (city_id) REFERENCES location.city (id)
);

CREATE TABLE IF NOT EXISTS info.photo
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id         INT      NOT NULL,
    url             VARCHAR(1024) NOT NULL,
    sequence_number SMALLINT NOT NULL,

    CONSTRAINT fk_photo_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),

    UNIQUE (club_id, sequence_number),
    UNIQUE (club_id, url)
);

CREATE TABLE IF NOT EXISTS info.game_club
(
    club_id INT      NOT NULL,
    game_id SMALLINT NOT NULL,

    CONSTRAINT fk_game_club_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),
    CONSTRAINT fk_game_club_game
        FOREIGN KEY (game_id) REFERENCES games.game (id),

    PRIMARY KEY (club_id, game_id)
);

CREATE TABLE IF NOT EXISTS info.price
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id          INT           NOT NULL,
    duration_minutes SMALLINT      NOT NULL,
    "value"          NUMERIC(8, 2) NOT NULL,

    CONSTRAINT fk_price_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),

    UNIQUE (club_id, duration_minutes)
);

CREATE TABLE IF NOT EXISTS info.work_schedule
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     INT      NOT NULL,
    day_of_week SMALLINT NOT NULL,
    open_time   TIME,
    close_time  TIME,
    is_work_day BOOLEAN  NOT NULL,

    CONSTRAINT fk_work_schedule_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),

    UNIQUE (club_id, day_of_week)
);

CREATE TABLE IF NOT EXISTS info.work_schedule_exception
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id     INT     NOT NULL,
    date        DATE    NOT NULL,
    open_time   TIME,
    close_time  TIME,
    is_work_day BOOLEAN NOT NULL,
    description VARCHAR(1024),

    CONSTRAINT fk_work_schedule_exception_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),

    UNIQUE (club_id, date)
);

--------------------------------------------------------------------------------------------
-- Tables in hr schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS hr.employee
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname       VARCHAR(100)       NOT NULL,
    name          VARCHAR(100)       NOT NULL,
    patronymic    VARCHAR(100),
    phone         VARCHAR(32) UNIQUE NOT NULL,
    password      VARCHAR(1024),
    need_password BOOLEAN            NOT NULL,
    is_blocked    BOOLEAN            NOT NULL
);

CREATE TABLE IF NOT EXISTS hr.employee_club
(
    club_id       INT           NOT NULL,
    employee_id   BIGINT        NOT NULL,
    employee_role VARCHAR(32)   NOT NULL,

    CONSTRAINT fk_employee_club_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),
    CONSTRAINT fk_employee_club_employee
        FOREIGN KEY (employee_id) REFERENCES hr.employee (id),

    PRIMARY KEY (club_id, employee_id, employee_role)
);

--------------------------------------------------------------------------------------------
-- Tables in clients schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS clients.client
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100)       NOT NULL,
    phone      VARCHAR(32) UNIQUE NOT NULL,
    password   VARCHAR(1024)      NOT NULL,
    is_blocked BOOLEAN            NOT NULL
);

--------------------------------------------------------------------------------------------
-- Tables in bookings schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS bookings.booking
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_id                      INT                     NOT NULL,
    client_id                    BIGINT,
    start_datetime               TIMESTAMP WITH TIME ZONE NOT NULL,
    end_datetime                 TIMESTAMP WITH TIME ZONE NOT NULL,
    cnt_equipment                SMALLINT                NOT NULL,
    price_value                  NUMERIC(10, 2)          NOT NULL,
    status                       VARCHAR(32)             NOT NULL,
    is_walk_in                   BOOLEAN                 NOT NULL,
    created_by_employee_id       BIGINT,
    pay_confirmed_by_employee_id BIGINT,
    note                         VARCHAR(4096),

    CONSTRAINT fk_booking_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),
    CONSTRAINT fk_booking_client
        FOREIGN KEY (client_id) REFERENCES clients.client (id),
    CONSTRAINT fk_booking_created_by_employee
        FOREIGN KEY (created_by_employee_id) REFERENCES hr.employee (id),
    CONSTRAINT fk_booking_pay_confirmed_by_employee
        FOREIGN KEY (pay_confirmed_by_employee_id) REFERENCES hr.employee (id)
);

--------------------------------------------------------------------------------------------
-- Tables in favorite schema
--------------------------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS favorite.client_favorite_club
(
    client_id BIGINT NOT NULL,
    club_id   INT    NOT NULL,

    CONSTRAINT fk_client_favorite_club_client
        FOREIGN KEY (client_id) REFERENCES clients.client (id),
    CONSTRAINT fk_client_favorite_club_club
        FOREIGN KEY (club_id) REFERENCES info.club (id),

    PRIMARY KEY (client_id, club_id)
);

